kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "tcpfailover.fullname" . }}
  annotations:
    app.openshift.io/vcs-uri: '{{ .Values.dockerSource.uri }}'
  labels:
    {{- include "tcpfailover.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ include "tcpfailover.fullname" . }}:{{ .Values.haproxyVersion }}'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: '{{ .Values.dockerSource.uri }}'
    contextDir: '{{ .Values.dockerSource.contextDir }}'
  triggers:
    - type: ConfigChange