kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/KevinLapagna/tcpfailover'
  name: {{ include "tcpfailover.fullname" . }}
  labels:
    {{- include "tcpfailover.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ include "tcpfailover.fullname" . }}:2'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/KevinLapagna/tcpfailover'
    contextDir: /docker/haproxy/