kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "tcpfailover.fullname" . }}-haproxy
  annotations:
    app.openshift.io/vcs-uri: '{{ .Values.dockerSource.uri }}'
  labels:
    {{- include "tcpfailover.labels" . | nindent 4 }}
data:
  haproxy.cfg: |+
    global
      log stdout format raw daemon notice
    
    defaults
      log global
      timeout connect 5s
      timeout client 5s
      timeout server 5s

    {{ range .Values.proxies }}
    listen {{ .name }}_failover
      bind :{{ .internalPort }}
      mode tcp
      option tcp-check
      server node1 {{ .mainServer }} check
      server node2 {{ .backupServer }} check backup
    {{ end }}
