kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-uri: 'https://github.com/KevinLapagna/tcpfailover'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"{{ include "tcpfailover.fullname" . }}:2"},"fieldPath":"spec.template.spec.containers[?(@.name==\"{{ include "tcpfailover.fullname" . }}\")].image","pause":"false"}]
  name: {{ include "tcpfailover.fullname" . }}
  labels:
    {{- include "tcpfailover.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tcpfailover.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tcpfailover.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: configmap-{{ include "tcpfailover.fullname" . }}
      containers:
        - name: {{ include "tcpfailover.fullname" . }}
          image: {{ include "tcpfailover.fullname" . }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate