kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: '{{ .Values.dockerSource.uri }}'
  name: {{ include "tcpfailover.fullname" . }}
  labels:
    {{- include "tcpfailover.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false