kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/KevinLapagna/tcpfailover'
  name: {{ include "tcpfailover.fullname" . }}
  labels:
    {{- include "tcpfailover.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false