{{- range .Values.proxies }}
{{- if .createRoute }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "tcpfailover.fullname" $ }}-{{ .name }}
  labels:
    {{- include "tcpfailover.labels" $ | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "tcpfailover.fullname" $ }}
  port:
    targetPort: {{ .name }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
{{- end }}
{{- end }}