kind: Service
apiVersion: v1
metadata:
  name: {{ include "tcpfailover.fullname" . }}
  labels:
    {{- include "tcpfailover.labels" . | nindent 4 }}
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/KevinLapagna/tcpfailover'
spec:
  ports:
  - name: ldaps
    protocol: TCP
    port: 636
    targetPort: 8636
  - name: ldap
    protocol: TCP
    port: 389
    targetPort: 8389
  type: ClusterIP
  selector:
    {{- include "tcpfailover.selectorLabels" . | nindent 4 }}