kind: Service
apiVersion: v1
metadata:
  name: {{ include "tcpfailover.fullname" . }}-loadbalancer
  labels:
    {{- include "tcpfailover.labels" . | nindent 4 }}
  annotations:
    app.openshift.io/vcs-uri: '{{ .Values.dockerSource.uri }}'
spec:
  ports:
    {{- include "tcpfailover.servicePorts" . | indent 4 }}
  type: LoadBalancer
  selector:
    {{- include "tcpfailover.selectorLabels" . | nindent 4 }}
