# Default values for tcpfailover.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

vcsUri: https://github.com/KevinLapagna/tcpfailover

haproxyVersion: 2

proxies:
  - name: ldaps
    internalPort: 8636
    externalPort: 636
    mainServer: example.com:443
    backupServer: example.org:443
    createRoute: true
  - name: ldap
    internalPort: 8389
    externalPort: 389
    mainServer: example.com:80
    backupServer: example.org:80
    createRoute: false